"""Authored comprehension questions. All numbers and messages are teaching examples."""

QUESTIONS = [
    dict(id='state', stage='Understand the interface',
         question='A customer writes “The export button crashes.” What belongs in the state?',
         options=['The customer message and relevant evidence', 'The answer “technical” that we want the model to choose', 'Our routing threshold of 0.85 alone'],
         correct=0, hint='State is what the model gets to examine.',
         explanation='State supplies evidence. The question and criteria describe the judgment. The routing threshold belongs to the application policy.',
         feedback=['', 'Putting the desired answer in the evidence can leak the label instead of teaching a real judgment.', 'A threshold describes when to act; it does not tell the model what happened.'],
         lesson='01_jev_basics', lesson_title='01 · State and typed questions'),
    dict(id='choice', stage='Understand the interface',
         question='You need one primary queue: billing, technical, or other. Which question type fits?',
         options=['Score', 'Choice', 'Noul'], correct=1,
         hint='The alternatives are named categories, with no low-to-high order.',
         explanation='Choice compares the supplied alternatives and returns a selected option plus probabilities. Write descriptions that distinguish the queues.',
         feedback=['The queues are categories rather than positions on an ordered scale.', '', 'A yes/no judgment does not directly select one of three queues.'],
         lesson='01_jev_basics', lesson_title='01 · Choice'),
    dict(id='noul', stage='Understand the interface',
         question='You ask “Does this message explicitly request a refund?” Which type fits?',
         options=['Choice over all support queues', 'Score from 0 to 2', 'Noul'], correct=2,
         hint='Think about whether the question has a positive and a negative answer.',
         explanation='Noul reports the probability of the positive answer to a yes/no question. The program can apply a threshold to that number.',
         feedback=['A queue question asks about the topic; it does not answer whether a refund was explicitly requested.', 'An ordered severity scale answers a different question.', ''],
         lesson='01_jev_basics', lesson_title='01 · Noul'),
    dict(id='rubric', stage='Understand the interface',
         question='A rubric has 0 = no disruption, 1 = partial disruption, 2 = fully blocked. Which type fits?',
         options=['Score', 'Noul', 'Choice with alphabetically ordered queue names'], correct=0,
         hint='These labels are levels along an ordered scale.',
         explanation='Score uses ordered rubric levels and returns their expected position. The meaning of each level should be clear.',
         feedback=['', 'A yes/no output would discard the distinction between partial and full disruption.', 'An alphabetical order of categories is not a meaningful severity scale.'],
         lesson='01_jev_basics', lesson_title='01 · Score'),
    dict(id='expectation', stage='Read the numbers',
         question='The probabilities for levels 0, 1, and 2 are 5%, 25%, and 70%. What is the expected score?',
         options=['2, because it is the most likely level', '1.65, from 0 × 0.05 + 1 × 0.25 + 2 × 0.70', '0.70, the probability of level 2'],
         correct=1, hint='Average the levels using their probabilities as weights.',
         explanation='The weighted average is 1.65. The most likely level is 2, but selecting that level and averaging the distribution are different calculations.',
         feedback=['That is the most likely level. The expected score also accounts for the other possible levels.', '', 'That is one probability, rather than an average of the levels.'],
         lesson='01_jev_basics', lesson_title='01 · Calculate a Score'),
    dict(id='threshold', stage='Read the numbers',
         question='Technical has probability 0.90. Our rule routes only when the largest probability is at least 0.95. What happens?',
         options=['Route to technical because it is largest', 'Change the model estimate to 0.95', 'Send the case for review'],
         correct=2, hint='Compare 0.90 with the threshold before taking the action.',
         explanation='The estimate stays 0.90 and the winning queue stays technical. The application sends the case for review because 0.90 is below 0.95.',
         feedback=['The winning label is technical, but the action also has to satisfy the policy.', 'Changing a decision rule does not change the model output.', ''],
         lesson='01_jev_basics', lesson_title='01 · Prediction and policy'),
    dict(id='validity', stage='Read the numbers',
         question='“billing” is an allowed output, but the message describes an export crash. What did the type check establish?',
         options=['The output has an allowed form', 'The model understood the message correctly', 'The program is authorized to issue a refund'],
         correct=0, hint='A format check can inspect the allowed values without knowing the right answer.',
         explanation='The output is structurally valid. Accuracy needs a reference judgment, and authorization needs the application’s permission rules.',
         feedback=['', 'A valid label can still be the wrong label.', 'A valid model output does not grant permissions.'],
         lesson='04_workflows_and_related_models', lesson_title='04 · Judgments and rules'),
    dict(id='calibration', stage='Read the numbers',
         question='A calibrated model repeatedly gives 80% for comparable yes/no cases. What should happen across many such cases?',
         options=['Every case is yes', 'About 80% are yes, with sampling variation', 'Exactly 80 out of every 100 are yes'],
         correct=1, hint='A probability describes a pattern across outcomes, not a promise for one outcome.',
         explanation='Calibration compares stated probabilities with observed frequencies across many predictions. Individual cases can be negative, and finite groups fluctuate.',
         feedback=['The remaining probability allows negative outcomes.', '', 'Sampling variation means a finite group need not have exactly the expected count.'],
         lesson='03_calibration_and_decisions', lesson_title='03 · Calibration'),
    dict(id='cost', stage='Build and evaluate',
         question='p(yes) = 0.90. Acting yes costs 4 if wrong; acting no costs 1 if wrong. Perfect review costs 0.20. Correct actions cost 0. Which is cheapest in expectation?',
         options=['Act yes: expected cost 0.40', 'Act no: expected cost 0.90', 'Review: cost 0.20'],
         correct=2, hint='Compare (1 − 0.90) × 4, 0.90 × 1, and 0.20.',
         explanation='Review has the lowest expected cost: 0.20 versus 0.40 and 0.90. This result assumes calibrated probabilities and perfectly accurate review.',
         feedback=['Yes is the more likely outcome, but the cost of a wrong yes makes review cheaper here.', 'The expected cost of a wrong no is 0.90, the highest of these three.', ''],
         lesson='03_calibration_and_decisions', lesson_title='03 · Expected action costs'),
    dict(id='splits', stage='Build and evaluate',
         question='You have trained the model and need to choose a routing threshold. Which split should you use?',
         options=['Validation; then assess the frozen system on test', 'Test; keep changing the threshold until the mistakes disappear', 'All labeled examples, then report the same examples as a fresh test'],
         correct=0, hint='Keep the final assessment separate from decisions about settings.',
         explanation='Use validation data to choose the threshold. Reserve test data to assess the frozen model and policy. Repeated tuning on test examples weakens that assessment.',
         feedback=['', 'That turns the test set into tuning data.', 'Fitting and assessing on the same examples does not measure performance on fresh cases.'],
         lesson='07_text_routing_capstone', lesson_title='07 · Training, validation, and test'),
    dict(id='wordorder', stage='Build and evaluate',
         question='“The payment failed, not the export.” and “The export failed, not the payment.” have identical bag-of-words features. Can a deterministic classifier using only those features distinguish them?',
         options=['Yes, if we lower temperature enough', 'No; the representation removed the distinguishing word order', 'Yes, by increasing the confidence threshold'],
         correct=1, hint='The classifier sees the same feature vector for both messages.',
         explanation='Identical input features produce identical outputs in this deterministic model. Word order and the scope of “not” matter here; temperature or thresholds cannot restore discarded information.',
         feedback=['Changing concentration cannot recover information missing from the features.', '', 'A threshold can send both cases to review, but cannot make their predictions different.'],
         lesson='07_text_routing_capstone', lesson_title='07 · Inspect the minimal-pair failure'),
    dict(id='evidence', stage='Build and evaluate',
         question='Our local classifier scores every option in one matrix operation. What does that experiment establish?',
         options=['That Jev must use our exact weight matrix and training method', 'That our local accuracy is a Jev benchmark', 'How one small teaching classifier can compute bounded decisions'],
         correct=2, hint='Ask which system was actually measured.',
         explanation='The experiment demonstrates our constructed classifier. The provider documentation describes Jev’s external behavior; the toy does not establish proprietary internals or performance.',
         feedback=['Different implementations can expose similar interfaces.', 'We measured the local toy on fictional data, not Jev.', ''],
         lesson='06_architecture_and_training_lab', lesson_title='06 · Mechanisms and evidence'),
]
